-   id: check-added-large-files
    name: Check for added large files
    description: Prevent giant files from being committed
    entry: check-added-large-files
    language: python
    # Match all files
    files: ''
-   id: check-byte-order-marker
    name: Check for byte-order marker
    description: Forbid files which have a UTF-8 byte-order marker
    entry: check-byte-order-marker
    language: python
    files: '\.py$'
-   id: check-case-conflict
    name: Check for case conflicts
    description: Check for files that would conflict in case-insensitive filesystems
    entry: check-case-conflict
    language: python
    # Match all files
    files: ''
-   id: check-docstring-first
    name: Check docstring is first
    description: Checks a common error of defining a docstring after code.
    entry: check-docstring-first
    language: python
    files: \.py$
-   id: check-yaml
    name: Check Yaml
    description: This hook checks yaml files for parseable syntax.
    entry: check-yaml
    language: python
    files: \.(yaml|yml|eyaml)$
-   id: debug-statements
    name: Debug Statements (Python)
    description: This hook checks that debug statements (pdb, ipdb, pudb) are not imported on commit.
    entry: debug-statement-hook
    language: python
    files: \.py$
-   id: end-of-file-fixer
    name: Fix End of Files
    description: Ensures that a file is either empty, or ends with one newline.
    entry: end-of-file-fixer
    language: python
    files: \.(asciidoc|adoc|coffee|cpp|css|c|ejs|erb|groovy|h|haml|hh|hpp|hxx|html|in|j2|jade|json|js|less|markdown|md|ml|mli|pp|py|rb|rs|R|scala|scss|sh|slim|tex|tmpl|ts|txt|yaml|yml)$
-   id: fix-encoding-pragma
    name: Fix python encoding pragma
    language: python
    entry: fix-encoding-pragma
    description: 'Add # -*- coding: utf-8 -*- to the top of python files'
    files: \.py$
-   id: flake8
    name: Flake8
    description: This hook runs flake8.
    entry: flake8
    language: python
    files: \.py$
-   id: trailing-whitespace
    name: Trim Trailing Whitespace
    description: This hook trims trailing whitespace.
    entry: trailing-whitespace-fixer
    language: python
    files: \.(asciidoc|adoc|coffee|cpp|css|c|ejs|erb|groovy|h|haml|hh|hpp|hxx|html|in|j2|jade|json|js|less|markdown|md|ml|mli|pp|py|rb|rs|R|scala|scss|sh|slim|tex|tmpl|ts|txt|yaml|yml)$
